### ISSUE TITLE
Unable to forward Payload to CBPI

### ISSUE THREAD

**Issue by Glider95** [InnuendoPi/MQTTDevice4#1]
Hello,

After successful installation of CBPI V4 latest version and MQTTDevice V4.10 (even tried Development V4.13), I am unable to forward MQTT Sensor value to CBPI despite being connected:
![Sensor screen](https://user-images.githubusercontent.com/36504054/151992248-417f5ccd-77d6-4430-a342-2a12ed0d8145.PNG)

![Sensor detail](https://user-images.githubusercontent.com/36504054/151992262-01ba5004-5cb7-4670-a183-1feb232ba224.PNG)
![MQTT Screen](https://user-images.githubusercontent.com/36504054/151992399-5915cebf-b981-4ecb-94fd-b9a05ad61ed4.PNG)
![MQTT Sensor detail](https://user-images.githubusercontent.com/36504054/151992489-b186fc9f-47ba-4fac-bc85-bd63db8e7ede.PNG)

I am bit confused regarding debug output. Should I use Arduino IDE Serial output ?

Thank you,

**Comment by InnuendoPi** [comment]
On CBPi4 side please try Sensor.Value (Sensor dot Value)
