### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by appSoluteDE** [InnuendoPi/MQTTDevice4#3]
The current version can not be compiled due to missing implementations:

> ...\1_LOOP.ino: In function 'void loop()':
1_LOOP:31:5: error: 'runAutoTune' was not declared in this scope; did you mean 'autoTune'?
   31 |     runAutoTune();
      |     ^~~~~~~~~~~
      |     autoTune
...\7_WEB.ino: In function 'void handleSetMash()':
7_WEB:511:5: error: 'initMashPlan' was not declared in this scope
  511 |     initMashPlan();
      |     ^~~~~~~~~~~~
7_WEB:512:5: error: 'readMash' was not declared in this scope
  512 |     readMash();
      |     ^~~~~~~~
...\7_WEB.ino: In function 'void handleRezeptUp()':
7_WEB:594:7: error: 'initMashPlan' was not declared in this scope
  594 |       initMashPlan();
      |       ^~~~~~~~~~~~
7_WEB:595:7: error: 'readMash' was not declared in this scope
  595 |       readMash();
      |       ^~~~~~~~
7_WEB:599:7: error: 'BtnImportKBH2' was not declared in this scope
  599 |       BtnImportKBH2();
      |       ^~~~~~~~~~~~~
7_WEB:601:7: error: 'BtnImportMMUM' was not declared in this scope
  601 |       BtnImportMMUM();
      |       ^~~~~~~~~~~~~
...\7_WEB.ino: In function 'void handleBtnPower()':
7_WEB:617:11: error: 'startAutoTune' was not declared in this scope; did you mean 'autoTune'?
  617 |           startAutoTune();
      |           ^~~~~~~~~~~~~
      |           autoTune
7_WEB:631:11: error: 'resetPID' was not declared in this scope
  631 |           resetPID();
      |           ^~~~~~~~
...\8_CONFIGFILE.ino: In function 'bool loadConfig()':
8_CONFIGFILE:154:3: error: 'readMash' was not declared in this scope
  154 |   readMash();
      |   ^~~~~~~~
...\990_tickerCallback.ino: In function 'void tickerDispCallback()':
990_tickerCallback:45:47: error: 'calcRemaining' was not declared in this scope
   45 |       currentStepRemain_text.attribute("txt", calcRemaining().c_str());
      |                                               ^~~~~~~~~~~~~
990_tickerCallback:88:38: error: 'calcRemaining' was not declared in this scope
   88 |       p1remain_text.attribute("txt", calcRemaining().c_str());
      |                                      ^~~~~~~~~~~~~
...\990_tickerCallback.ino: In function 'void tickerMashCallback()':
990_tickerCallback:256:3: error: 'handleMash' was not declared in this scope; did you mean 'handleSetMash'?
  256 |   handleMash();
      |   ^~~~~~~~~~
      |   handleSetMash
...\990_tickerCallback.ino: In function 'void tickerPIDCallback()':
990_tickerCallback:280:5: error: 'checkTemp' was not declared in this scope
  280 |     checkTemp();
      |     ^~~~~~~~~

**Comment by InnuendoPi** [comment]
Missing ino files not published yet
