### ISSUE TITLE
MQTT website is unresponsive and doesn't look right

### ISSUE THREAD

**Issue by bowlerhatman** [InnuendoPi/MQTTDevice4#5]
![Screenshot_20230427-183509_Chrome](https://user-images.githubusercontent.com/712624/234807299-50f0a3a3-eab8-4afd-bbe7-1daa545b97bb.jpg)

Hi there,
I've just got this installed, and am now trying to configure a sensor to read temperature. However, the website served up by the ESP8266 doesn't look quite like that shown on your setup guide. In addition, the dropdowns for selecting a sensor do not appear to do anything. Can you please give me a pointer about how to go about rectifying this?

**Comment by InnuendoPi** [comment]
Looks like you do not have css file on your device. check the files in folder data or reflash.

**Comment by bowlerhatman** [comment]
I downloaded a new copy of the repo and reflashed, but I got the same results. Can you please indicate what you mean by 'check the files in folder data'?

I'm also having to guess a bit on how to upload, I'm using the Arduino IDE, and uploading MQTTdevice4.ino - is there anything else I should be doing? I can't see anything further specified, but I'm also not sure why it's not working out of the box.

Thanks,
Frazer

**Comment by InnuendoPi** [comment]
Maybe your phone does not support javascript or something similar. i have checked latest version with no problems.
<img width="585" alt="website" src="https://user-images.githubusercontent.com/46191753/235286994-58a5f2dd-4519-424d-8326-3c66bf98b315.png">
file handling: ip/edit (eg http://192.168.1.14/edit). if you need support, check out forum https://hobbybrauer.de

**Comment by bowlerhatman** [comment]
I got it working in the end. I reflashed, and had the same issue. Then I went to the "file" link and uploaded the contents of the data folder from the repo, and now it seems to be working fine. I'm not sure why these files didn't upload as part of flashing, but it solved my problem anyway. Thanks for your time!
